# .envのインポート
spring.config.import=optional:file:.env[.properties]

# project
spring.application.name=PepperCookingAssistant

# postgres
spring.jpa.database=POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:${DB_HOST_MACHINE_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}