CREATE TABLE users (
	"id" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"name" VARCHAR(50) NOT NULL,
	"email" VARCHAR(255) NOT NULL UNIQUE,
	"password_hash" VARCHAR(255) NOT NULL,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"deleted_at" TIMESTAMP,
	"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ingredient_categories (
	"id" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"category_name" VARCHAR(50) NOT NULL UNIQUE,
	"reading" VARCHAR(50),
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"deleted_at" TIMESTAMP,
	"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ingredients (
	"id" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"name" VARCHAR(50) NOT NULL,
	"reading" VARCHAR(50),
	"default_unit" VARCHAR(20),
	"category_id" BIGINT REFERENCES ingredient_categories(id),
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"deleted_at" TIMESTAMP,
	"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stocks (
	"id" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	"ingredient_id" BIGINT NOT NULL REFERENCES ingredients(id),
	"user_id" BIGINT NOT NULL REFERENCES users(id),
	"quantity" numeric(10,2) NOT NULL,
	"expiration_date" date NOT NULL,
	"created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"deleted_at" TIMESTAMP,
	"updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);